export const LOCATION_ACTION = 'LOCATION_ACTION'
export const LOCATION_ACTION_CREATE = 'LOCATION_ACTION_CREATE'
export const LOCATION_ACTION_DELETE = 'LOCATION_ACTION_DELETE'
export const LOCATION_ACTION_SEARCH = 'LOCATION_ACTION_SEARCH'
export const LOCATION_ACTION_UPDATE = 'LOCATION_ACTION_UPDATE'

